// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvahgolbbtlghbtneepb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2YWhnb2xiYnRsZ2hidG5lZXBiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNjQ2ODAsImV4cCI6MjA2NDY0MDY4MH0.ZUWIm4C1UZaH-trcj-O9c__vhC6zgUhDBzm8HI8uik4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);